### ISSUE TITLE
Constructor Error PolyClosed.h

### ISSUE THREAD

**Issue by rbledsaw3** [planetchili/HUGS#2]
Just cloned this fresh today. Tried to build without changing anything and I'm getting quite a few errors pertaining to PolyClosed.h around line 61-65. See attached images.
<img width="518" alt="intellisense" src="https://cloud.githubusercontent.com/assets/13861003/11361805/6abc7eea-9255-11e5-8429-3a1c4347d959.PNG">
<img width="759" alt="error" src="https://cloud.githubusercontent.com/assets/13861003/11361804/6ab92524-9255-11e5-9759-0c749b75fb99.PNG">

**Comment by rbledsaw3** [comment]
Nvm, looks like this was corrected in the following video. I'm a fucking idiot, lol.

**Comment by planetchili** [comment]
Hey man thanks for the heads up. It seems that containers of const elements were always bad mojo, but VC++ up to 2013RTM still accepted them. I have been weaning myself off of using const for member data and for container types, but this is going to cause a problem for people who try and build the code from older videos with newer compilers :/
